services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - whatsapp-clone
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 9090:8080
    networks:
      - whatsapp-clone
    command: start-dev

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local